POST http://localhost:7071/api/PyPropsSIAll HTTP/1.1
content-type: application/json

{
    "Fluid": "R134a",
    "Name": "Volkan",
    "Prop1": 6,
    "Prop2": 1,
    "Value1": 0.45399999999999996,
    "Value2": 285.54999999999995
}